const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const intro=document.getElementById('intro'),finish=document.getElementById('finish'),hud=document.getElementById('hud'),toast=document.getElementById('toast'),count=document.getElementById('count'),talk=document.getElementById('talk'),speaker=document.getElementById('speaker'),message=document.getElementById('message');
const W=960,H=540, keys={}, stars=[{x:170,y:180},{x:335,y:115},{x:510,y:220},{x:700,y:135},{x:825,y:320},{x:585,y:405},{x:240,y:390}], friends=[{x:120,y:370,name:'a coruja',line:'O vento levou uma estrela para o lado das pedras.'},{x:450,y:370,name:'o cervo',line:'A água sabe o caminho. Pergunte ao rio.'},{x:760,y:420,name:'a árvore antiga',line:'Toda luz que você escuta também escuta você.'}];let player,found,playing=false,last=0,sound=true,near=-1;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.getElementById('startButton').onclick=()=>{intro.classList.add('hidden');hud.classList.remove('hidden');reset();playing=true;requestAnimationFrame(loop)};document.getElementById('againButton').onclick=()=>{finish.classList.add('hidden');hud.classList.remove('hidden');reset();playing=true;requestAnimationFrame(loop)};document.getElementById('soundButton').onclick=()=>{sound=!sound;document.querySelector('.sound span').textContent=sound?'som':'mudo'};
function reset(){player={x:90,y:270,dx:0,dy:0};found=new Set();count.textContent='0'}
function loop(t){if(!playing)return;let dt=Math.min((t-last)/16,2);last=t;update(dt);draw(t);requestAnimationFrame(loop)}
function update(dt){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let n=Math.hypot(x,y)||1;player.x=Math.max(35,Math.min(925,player.x+x/n*2.5*dt));player.y=Math.max(90,Math.min(485,player.y+y/n*2.5*dt));near=friends.findIndex(f=>Math.hypot(player.x-f.x,player.y-f.y)<45);if(keys[' ']&&near>-1&&!keys._space){keys._space=true;speak(friends[near].name,friends[near].line)}if(!keys[' '])keys._space=false;stars.forEach((s,i)=>{if(!found.has(i)&&Math.hypot(player.x-s.x,player.y-s.y)<25){found.add(i);count.textContent=found.size;showToast(found.size===7?'A última estrela encontrou você.':'Você ouviu um brilho entre as folhas.');if(found.size===7)setTimeout(()=>{playing=false;hud.classList.add('hidden');finish.classList.remove('hidden')},1300)}})}
function speak(who,what){speaker.textContent=who;message.textContent=what;talk.classList.remove('hidden');clearTimeout(speak.t);speak.t=setTimeout(()=>talk.classList.add('hidden'),3600)}
function showToast(t){toast.textContent=t;toast.classList.remove('hidden');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.add('hidden'),1900)}
function draw(t){let g=ctx;g.fillStyle='#183443';g.fillRect(0,0,W,H);g.fillStyle='#203f48';g.fillRect(0,305,W,235);g.fillStyle='#294d4a';for(let i=0;i<18;i++){let x=(i*71)%W;tree(x,300-(i%3)*20,1+(i%2)*.18)}g.fillStyle='#315b51';g.fillRect(0,420,W,120);g.fillStyle='#3b6959';for(let i=0;i<55;i++){let x=(i*83+30)%W,y=430+(i*37)%88;g.fillRect(x,y,3,4);g.fillRect(x+4,y-3,2,3)}g.fillStyle='#e8c98b';g.globalAlpha=.85;for(let i=0;i<30;i++){let x=(i*137)%W,y=36+(i*73)%250;g.fillRect(x,y,2,2)}g.globalAlpha=1;friends.forEach(f=>animal(f.x,f.y));stars.forEach((s,i)=>{if(!found.has(i))star(s.x,s.y,t,i)});naya(player.x,player.y,t)}
function animal(x,y){ctx.fillStyle='#b9b58a';ctx.fillRect(x-9,y-8,18,13);ctx.fillRect(x-6,y-15,4,7);ctx.fillRect(x+2,y-15,4,7);ctx.fillStyle='#172c36';ctx.fillRect(x-5,y-4,2,2);ctx.fillRect(x+3,y-4,2,2)}
function tree(x,y,scale){ctx.fillStyle='#1d3742';ctx.fillRect(x-8*scale,y,16*scale,115*scale);ctx.fillStyle='#254940';ctx.fillRect(x-42*scale,y-33*scale,84*scale,36*scale);ctx.fillRect(x-29*scale,y-58*scale,58*scale,30*scale);ctx.fillStyle='#31574e';ctx.fillRect(x-24*scale,y-45*scale,13*scale,12*scale);ctx.fillRect(x+16*scale,y-24*scale,16*scale,10*scale)}
function star(x,y,t,i){let pulse=Math.sin(t/330+i)*2;ctx.save();ctx.translate(x,y);ctx.fillStyle='#f9bd7d';ctx.globalAlpha=.16;ctx.fillRect(-17-pulse,-17-pulse,34+pulse*2,34+pulse*2);ctx.globalAlpha=1;ctx.fillStyle='#ffe2a1';ctx.beginPath();for(let a=0;a<10;a++){let r=a%2?5:12;let ang=-Math.PI/2+a*Math.PI/5;ctx.lineTo(Math.cos(ang)*r,Math.sin(ang)*r)}ctx.fill();ctx.restore()}
function naya(x,y,t){ctx.save();ctx.translate(Math.round(x),Math.round(y));let bob=Math.sin(t/180)*2;ctx.translate(0,bob);ctx.fillStyle='#ef8b6b';ctx.fillRect(-11,-2,22,25);ctx.fillStyle='#f7c19a';ctx.fillRect(-8,-20,16,18);ctx.fillStyle='#251c32';ctx.fillRect(-6,-15,3,3);ctx.fillRect(4,-15,3,3);ctx.fillStyle='#f3a56e';ctx.fillRect(-14,-24,28,6);ctx.fillRect(-10,-28,20,5);ctx.fillStyle='#db6a62';ctx.fillRect(-13,22,-1,8);ctx.fillRect(5,22,8,8);ctx.restore()}
